version: '2'
services:
    digitorch-app:
        image: digitorch
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://digitorch-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=DigitOrch
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://digitorch-elasticsearch:9200
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
        ports:
            - 8080:8080
    digitorch-mongodb:
        extends:
            file: mongodb.yml
            service: digitorch-mongodb
    digitorch-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: digitorch-elasticsearch
    kafka:
        extends:
            file: kafka.yml
            service: kafka
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=kafka
    zookeeper:
        extends:
            file: kafka.yml
            service: zookeeper
